export const ADD_ITEM_TO_WISHLIST_REQUEST = 'ADD_ITEM_TO_WISHLIST_REQUEST';
export const ADD_ITEM_TO_WISHLIST_SUCCESS = 'ADD_ITEM_TO_WISHLIST_SUCCESS';
export const ADD_ITEM_TO_WISHLIST_FAILURE = 'ADD_ITEM_TO_WISHLIST_FAILURE';

export const GET_USER_WISHLIST_REQUEST = 'GET_USER_WISHLIST_REQUEST';
export const GET_USER_WISHLIST_SUCCESS = 'GET_USER_WISHLIST_SUCCESS';
export const GET_USER_WISHLIST_FAILURE = 'GET_USER_WISHLIST_FAILURE';

export const REMOVE_WISHLIST_ITEM_REQUEST = 'REMOVE_WISHLIST_ITEM_REQUEST';
export const REMOVE_WISHLIST_ITEM_SUCCESS = 'REMOVE_WISHLIST_ITEM_SUCCESS';
export const REMOVE_WISHLIST_ITEM_FAILURE = 'REMOVE_WISHLIST_ITEM_FAILURE';
